name: KitBattle
author: Wazup92
version: 9.9.3
api-version: 1.13
main: me.wazup.kitbattle.Kitbattle
softdepend: [Vault, PlaceholderAPI, TitleManager, MVdWPlaceholderAPI, AdvancedEnchantments, HolographicDisplays, CrackShot, DecentHolograms, ItemsAdder, ItemEdit]
commands:
  kitbattle:
    description: Main command!
    aliases: [kb]