# # # # # # # # # # # # # # # # # # # # # # 
#           Made by Wazup92               #
#     If you really like the plugin       #
#     Then please dont forget to leave    #
#        A positive 5 stars review!       #
# # # # # # # # # # # # # # # # # # # # # # 
# If you enable Check-For-General-Notifications, I will be able to send you in-game notifications of events such as plugin sales or important messages.
# These notifications only show once every 6 hours upon joining the server.

Check-For-Updates: true
Check-For-General-Notifications: true

use-UUID: false
Map-Load-Delay: 10
Starting-Coins: 1000

Scoreboard-Enabled: true
Notify-When-Cooldown-Off: true
Kill-Coins-Contribution: true
Do-Players-Drop-Items-On-Death: false
Can-Players-Drop-Items-On-Ground: false
Can-Players-Pick-Items-On-Ground: false
Disable-Interactions-In-Spawn-Region: false
Do-Players-Lose-Hunger: false
Purchaseable-Kits-Are-Permanent: true
Show-Health-Below-Name: true
Starting-Amount-Of-Kit-Unlockers: 2
Respawn-Screen-On-Death: false
Spawn-Teleport-Countdown-Seconds: 5
Spectate-Countdown-Seconds: 5
Earned-Coins-Per-Kill: 8
Minimum-Exp-Per-Kill: 2
Maximum-Exp-Per-Kill: 5
Sponge-Boost-Upwards: 1.5
Update-Leaderboard-Every-Minutes: 60
Sell-Value: 0.33
Challenge-Lives: 2
Challenge-Respawn-Protection-Seconds: 5
Minimum-Bounty: 25
Soup-Auto-Disappear: false
Fall-Damage-Enabled: true
Open-Kits-Menu-On-Respawn: false
Broadcast-Rank-Up: true
Show-Rank-In-Chat: true
Send-Death-Message-To-Everyone: true
Allow-Building: false
Soup-Drop-Sound: true
Sponge-Launch-Sound: true
Void-Instant-Death: true
Leave-Command-Timer: 3
Bounty-Set-Cooldown: 20
Soup-Sign-Cooldown: 20
Default-Kits:
- Pvp
Send-Killstreaks-To-Everyone: true
Killstreaks-Enabled: true
Deathstreaks-Enabled: true
use-Vault: false

Respawn-Effects:
  - 'BLINDNESS : 2 : 4'
  - 'SLOW : 1 : 4'

Combat-Log:
  enabled: true
  message: true
  duration: 15

Saving-Task:
  Enabled: true
  Save-Every-Minutes: 10

use-mysql: false
table-prefix: vexliokits_
mysql-host: localhost
mysql-port: 3306
mysql-database: database
mysql-username: root
mysql-password: root

Bungee-Mode: false
Shuffle-Every-In-Minutes: 30
Time-Shown-Before-Shuffle: [60, 30, 15, 10, 5, 4, 3, 2, 1]

ELO:
  Starting-Value: 1000
  Change-Factor: 40

Kit-Lores:
  Owned: [' ', '&d&lState: %statecolor%%state%', '&d&lRequires Permission: %permissioncolor%%requirespermission%', ' ', '&d- &b&nLeft click to equip &d/ &c&nRight click to sell']
  Shop: [' ', '&d&lState: %statecolor%%state%', '&d&lRequires Permission: %permissioncolor%%requirespermission%', ' ', '&c&nRight click to preview this kit!', ' ', '&6&lPrice: &e%price% &6coins!']

Tournaments:
  min-players: 7
  grace-period: 15
  countdown-length: 30
  max-time: 600
  celebration-length: 12
  fireworks-celebration: true
  winner-rewards:
  - 'vexliokits coins add %winner% 100'
  - 'vexliokits kitunlocker give %winner% 1'
  time-shown-during-countdown: [30, 15, 10, 5, 4, 3, 2, 1]
  grace-period-warnings: [15, 10, 5, 4, 3, 2, 1]
  end-warnings: [60, 30, 15, 10, 5, 4, 3, 2, 1]
  
Challenges:
  grace-length: 15
  max-time: 300
  celebration-length: 12
  fireworks-celebration: true
  winner-rewards:
  - 'vexliokits coins add %winner% 50'
  grace-period-warnings: [15, 10, 5, 4, 3, 2, 1]
  end-warnings: [60, 30, 15, 10, 5, 4, 3, 2, 1]
  kit-lock:
    enabled: false
    challenge-kit: Pvp
  
Create-Default-Kits: true

Aliases:
- kitpvp
- pvp
Allowed-Commands:
- vexliokits
- kits
- vk
- tell
- help
- t
- r

Hotbar-Items:
  Kit-Selector:
    enabled: true
    item: 'CHEST : name:&7Kit Selector (&aRight click!&7)'
    slot: 1
  Shop-Opener:
    enabled: true
    item: 'ANVIL : name:&7Shop (&aRight click!&7)'
    slot: 2
  Challenges-Item:
    enabled: true
    item: 'BLAZE_ROD : name:&6Challenges'
    slot: 5
  Trails-Opener:
    enabled: true
    item: 'ENCHANTED_BOOK : name:&eTrails &6[VIP]'
    slot: 7
  Profile-Item:
    enabled: true
    item: 'PAPER : name:&aStats'
    slot: 8
  Kit-Unlocker:
    enabled: true
    item: 'CHEST : name:&7Kit Unlocker! (&aRight click!&7)'
    slot: 9

Modifiers: ['2 : vexliokits.vip', '3 : vexliokits.ultravip']

Trails:
  enabled: true
  size: 2
  interval: 3

Action-Bar:
  enabled: true
  Ability-Cooldown:
    enabled: false
    update-speed: 11
    time-format: '0.0'

Titles-Enabled: true

Scoreboard-Title-Animation:
  enabled: false
  interval: 8
  frames: ['&b&l&nVexlioKits', '&e&l&nVexlioKits', '&b&l&nVexlioKits', '&a&l&nVexlioKits', '&b&l&nVexlioKits', '&c&l&nVexlioKits', '&e&l&nV&b&l&nexlioKits', '&b&l&nV&e&l&ne&b&l&nxlioKits', '&b&l&nVe&e&l&nx&b&l&nlioKits', '&b&l&nVex&e&l&nl&b&l&nioKits', '&b&l&nVexl&e&l&ni&b&l&noKits', '&b&l&nVexli&e&l&no&b&l&nKits', '&b&l&nVexlio&e&l&nK&b&l&nits', '&b&l&nVexlioK&e&l&ni&b&l&nts', '&b&l&nVexlioKi&e&l&nt&b&l&ns', '&b&l&nVexlioKit&e&l&ns']

Deathstreak-End-Commands: ['effect %player% resistance 1 2', 'effect %player% regeneration 1 2', 'effect %player% strength 1 1', 'effect %player% speed 1 1']

Custom-Maps:
  Tournament-Winner-Map:
    enabled: true
    texts:
      - 'Congratulations'
      - '   For winning!!!'
    image: 'https://i.imgur.com/FrgIjmJ.png'
  Challenge-Winner-Map:
    enabled: true
    texts:
      - 'Congratulations'
      - '   For winning!!!'
    image: 'https://i.imgur.com/FrgIjmJ.png'