name: VexlioKits
author: tp3x
version: 6.9
api-version: 1.13
main: eu.milujukockoholky.vexliokits.VexlioKits
softdepend: [Vault, PlaceholderAPI, TitleManager, AdvancedEnchantments, HolographicDisplays, DecentHolograms, ItemsAdder, ItemEdit]
commands:
  vexliokits:
    description: Main command!
    aliases: [vk]
  kits:
    description: Kits main command!
    aliases: [kitbattle, kb]
  spawn:
    description: Spawn command!